/**
 * Florida pool-yard plants and trees as placeable catalog items.
 *
 * Visual / 3D only — not sold on the estimate. A company can add a custom
 * landscaping line if they need to bill plantings.
 *
 * This is a production-builder palette (species that actually get planted
 * around Florida pools), not every plant that can survive in the state.
 * Invasives that are illegal to sell (Brazilian pepper, Australian pine,
 * melaleuca, air potato) are omitted on purpose.
 */

export type PlantColor = { r: number; g: number; b: number };

export type PlantGroup = "palms" | "trees" | "shrubs" | "tropical";

/**
 * Distinctive 3D habit — drives the mesh, not just a tinted box.
 * Names match field characters (crownshaft, costapalmate fan, etc.).
 */
export type PlantForm =
  | "fan_palm"
  | "feather_palm"
  | "royal_palm"
  | "coconut_palm"
  | "foxtail_palm"
  | "clumping_palm"
  | "travelers"
  | "saw_palmetto"
  | "live_oak"
  | "magnolia"
  | "crape_myrtle"
  | "citrus"
  | "cypress"
  | "pine"
  | "jacaranda"
  | "gumbo_limbo"
  | "sea_grape"
  | "frangipani"
  | "bottlebrush"
  | "broadleaf"
  | "round_shrub"
  | "variegated_shrub"
  | "flowering_shrub"
  | "hedge"
  | "rosette"
  | "cycad"
  | "bird_of_paradise"
  | "banana"
  | "elephant_ear"
  | "philodendron"
  | "cordyline"
  | "fern";

export type PlantBloom =
  | "none"
  | "saucer"
  | "cluster"
  | "trumpet"
  | "spike"
  | "bract"
  | "star"
  | "bird";

export type FloridaPlant = {
  id: string;
  name: string;
  botanical: string;
  group: PlantGroup;
  form: PlantForm;
  foliage: PlantColor;
  /** Secondary foliage (new growth, variegation, rusty magnolia underside). */
  foliageAlt?: PlantColor;
  trunk: PlantColor;
  flower?: PlantColor;
  bloom: PlantBloom;
  flowerSize: number;
  /** Typical installed size in mm (pool-yard scale, not forest giants). */
  widthMm: number;
  depthMm: number;
  heightMm: number;
  native?: boolean;
  description?: string;
};

const rgb = (r: number, g: number, b: number): PlantColor => ({ r, g, b });

const FT = 304.8;

export const PLANT_GROUP_LABELS: Record<PlantGroup, string> = {
  palms: "Palms",
  trees: "Trees",
  shrubs: "Shrubs & hedges",
  tropical: "Tropical accents",
};

export const PLANT_GROUPS: PlantGroup[] = [
  "palms",
  "trees",
  "shrubs",
  "tropical",
];

export const YARD_LANDSCAPE_STRUCTURE_IDS = [
  "planter",
  "trellis",
  "trellis_arbor",
] as const;

export const FLORIDA_PLANTS: FloridaPlant[] = [
  // --- Palms ---
  {
    id: "sabal_palmetto",
    name: "Cabbage palmetto",
    botanical: "Sabal palmetto",
    group: "palms",
    form: "fan_palm",
    foliage: rgb(48, 92, 52),
    trunk: rgb(108, 98, 82),
    bloom: "none",
    flowerSize: 0,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 18 * FT,
    native: true,
    description: "Florida state tree — costapalmate fans, fiber-wrapped trunk",
  },
  {
    id: "queen_palm",
    name: "Queen palm",
    botanical: "Syagrus romanzoffiana",
    group: "palms",
    form: "feather_palm",
    foliage: rgb(54, 122, 52),
    trunk: rgb(148, 146, 136),
    bloom: "none",
    flowerSize: 0,
    widthMm: 12 * FT,
    depthMm: 12 * FT,
    heightMm: 22 * FT,
    description: "Smooth gray trunk, plumose bright-green fronds",
  },
  {
    id: "royal_palm",
    name: "Royal palm",
    botanical: "Roystonea regia",
    group: "palms",
    form: "royal_palm",
    foliage: rgb(32, 86, 42),
    trunk: rgb(176, 174, 166),
    bloom: "none",
    flowerSize: 0,
    widthMm: 12 * FT,
    depthMm: 12 * FT,
    heightMm: 28 * FT,
    native: true,
    description: "Cement-gray self-cleaning trunk and a glossy green crownshaft",
  },
  {
    id: "coconut_palm",
    name: "Coconut palm",
    botanical: "Cocos nucifera",
    group: "palms",
    form: "coconut_palm",
    foliage: rgb(72, 128, 46),
    trunk: rgb(156, 130, 96),
    bloom: "none",
    flowerSize: 0,
    widthMm: 16 * FT,
    depthMm: 16 * FT,
    heightMm: 24 * FT,
    description: "Leaning ringed trunk, yellow-green fronds — coastal South Florida",
  },
  {
    id: "canary_date",
    name: "Canary Island date palm",
    botanical: "Phoenix canariensis",
    group: "palms",
    form: "feather_palm",
    foliage: rgb(48, 102, 52),
    trunk: rgb(92, 78, 62),
    bloom: "none",
    flowerSize: 0,
    widthMm: 18 * FT,
    depthMm: 18 * FT,
    heightMm: 20 * FT,
    description: "Stout diamond-cut trunk, stiff arching pinnate crown",
  },
  {
    id: "foxtail_palm",
    name: "Foxtail palm",
    botanical: "Wodyetia bifurcata",
    group: "palms",
    form: "foxtail_palm",
    foliage: rgb(58, 122, 62),
    trunk: rgb(150, 140, 122),
    bloom: "none",
    flowerSize: 0,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 18 * FT,
    description: "Self-cleaning gray trunk, bottlebrush / foxtail leaflets",
  },
  {
    id: "areca_palm",
    name: "Areca palm",
    botanical: "Dypsis lutescens",
    group: "palms",
    form: "clumping_palm",
    foliage: rgb(78, 140, 58),
    trunk: rgb(186, 168, 72),
    bloom: "none",
    flowerSize: 0,
    widthMm: 8 * FT,
    depthMm: 8 * FT,
    heightMm: 14 * FT,
    description: "Clumping golden-cane trunks — the classic Florida screen",
  },
  {
    id: "pygmy_date",
    name: "Pygmy date palm",
    botanical: "Phoenix roebelenii",
    group: "palms",
    form: "feather_palm",
    foliage: rgb(44, 96, 48),
    trunk: rgb(86, 74, 58),
    bloom: "none",
    flowerSize: 0,
    widthMm: 6 * FT,
    depthMm: 6 * FT,
    heightMm: 8 * FT,
    description: "Fine dark pinnate crown on a slender rough trunk",
  },
  {
    id: "bismarck_palm",
    name: "Bismarck palm",
    botanical: "Bismarckia nobilis",
    group: "palms",
    form: "fan_palm",
    foliage: rgb(168, 186, 178),
    foliageAlt: rgb(148, 168, 172),
    trunk: rgb(122, 118, 108),
    bloom: "none",
    flowerSize: 0,
    widthMm: 16 * FT,
    depthMm: 16 * FT,
    heightMm: 22 * FT,
    description: "Huge costapalmate fans in glaucous silver-blue",
  },
  {
    id: "washingtonia",
    name: "Mexican fan palm",
    botanical: "Washingtonia robusta",
    group: "palms",
    form: "fan_palm",
    foliage: rgb(56, 108, 52),
    trunk: rgb(140, 124, 98),
    bloom: "none",
    flowerSize: 0,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 32 * FT,
    description: "Very tall slender trunk, bright green palmate crown",
  },
  {
    id: "travelers_palm",
    name: "Traveler’s palm",
    botanical: "Ravenala madagascariensis",
    group: "palms",
    form: "travelers",
    foliage: rgb(48, 126, 52),
    trunk: rgb(128, 118, 100),
    bloom: "none",
    flowerSize: 0,
    widthMm: 14 * FT,
    depthMm: 6 * FT,
    heightMm: 18 * FT,
    description: "Not a true palm — banana-like paddles in a single plane",
  },
  {
    id: "saw_palmetto",
    name: "Saw palmetto",
    botanical: "Serenoa repens",
    group: "palms",
    form: "saw_palmetto",
    foliage: rgb(92, 122, 78),
    foliageAlt: rgb(168, 176, 148),
    trunk: rgb(96, 86, 70),
    bloom: "none",
    flowerSize: 0,
    widthMm: 8 * FT,
    depthMm: 8 * FT,
    heightMm: 5 * FT,
    native: true,
    description: "Low clumping fans, often silver-green, native understory",
  },

  // --- Trees ---
  {
    id: "live_oak",
    name: "Southern live oak",
    botanical: "Quercus virginiana",
    group: "trees",
    form: "live_oak",
    foliage: rgb(36, 64, 32),
    trunk: rgb(52, 44, 36),
    bloom: "none",
    flowerSize: 0,
    widthMm: 28 * FT,
    depthMm: 28 * FT,
    heightMm: 22 * FT,
    native: true,
    description: "Wide spreading evergreen oak — the classic Florida shade tree",
  },
  {
    id: "southern_magnolia",
    name: "Southern magnolia",
    botanical: "Magnolia grandiflora",
    group: "trees",
    form: "magnolia",
    foliage: rgb(18, 52, 26),
    foliageAlt: rgb(138, 92, 48),
    trunk: rgb(68, 56, 42),
    flower: rgb(248, 246, 238),
    bloom: "saucer",
    flowerSize: 1.4,
    widthMm: 14 * FT,
    depthMm: 14 * FT,
    heightMm: 20 * FT,
    native: true,
    description: "Glossy leaves with rusty undersides and dinner-plate white blooms",
  },
  {
    id: "crape_myrtle",
    name: "Crape myrtle",
    botanical: "Lagerstroemia indica",
    group: "trees",
    form: "crape_myrtle",
    foliage: rgb(52, 102, 48),
    trunk: rgb(188, 118, 96),
    flower: rgb(214, 88, 148),
    bloom: "cluster",
    flowerSize: 1.15,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 14 * FT,
    description: "Vase of mottled cinnamon trunks, summer flower panicles",
  },
  {
    id: "citrus_tree",
    name: "Citrus (orange)",
    botanical: "Citrus × sinensis",
    group: "trees",
    form: "citrus",
    foliage: rgb(26, 102, 40),
    trunk: rgb(96, 82, 64),
    flower: rgb(248, 246, 230),
    bloom: "star",
    flowerSize: 0.7,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 12 * FT,
    description: "Rounded glossy canopy with fruit — sweet orange as the type",
  },
  {
    id: "bald_cypress",
    name: "Bald cypress",
    botanical: "Taxodium distichum",
    group: "trees",
    form: "cypress",
    foliage: rgb(78, 122, 72),
    trunk: rgb(96, 78, 58),
    bloom: "none",
    flowerSize: 0,
    widthMm: 12 * FT,
    depthMm: 12 * FT,
    heightMm: 28 * FT,
    native: true,
    description: "Flared buttress, feathery deciduous conifer — wet sites",
  },
  {
    id: "slash_pine",
    name: "Slash pine",
    botanical: "Pinus elliottii",
    group: "trees",
    form: "pine",
    foliage: rgb(48, 86, 56),
    trunk: rgb(132, 88, 48),
    bloom: "none",
    flowerSize: 0,
    widthMm: 12 * FT,
    depthMm: 12 * FT,
    heightMm: 32 * FT,
    native: true,
    description: "Tall open crown, long needles — Florida’s common yellow pine",
  },
  {
    id: "tabebuia_pink",
    name: "Pink trumpet tree",
    botanical: "Handroanthus impetiginosus",
    group: "trees",
    form: "broadleaf",
    foliage: rgb(48, 102, 52),
    trunk: rgb(86, 72, 56),
    flower: rgb(214, 118, 168),
    bloom: "trumpet",
    flowerSize: 1.2,
    widthMm: 16 * FT,
    depthMm: 16 * FT,
    heightMm: 18 * FT,
    description: "Bare-branch pink trumpet flush in late winter / spring",
  },
  {
    id: "jacaranda",
    name: "Jacaranda",
    botanical: "Jacaranda mimosifolia",
    group: "trees",
    form: "jacaranda",
    foliage: rgb(82, 138, 72),
    trunk: rgb(102, 88, 68),
    flower: rgb(138, 98, 196),
    bloom: "cluster",
    flowerSize: 1.1,
    widthMm: 20 * FT,
    depthMm: 20 * FT,
    heightMm: 22 * FT,
    description: "Ferny bipinnate canopy, lavender-blue panicles",
  },
  {
    id: "gumbo_limbo",
    name: "Gumbo-limbo",
    botanical: "Bursera simaruba",
    group: "trees",
    form: "gumbo_limbo",
    foliage: rgb(70, 124, 58),
    trunk: rgb(204, 98, 52),
    bloom: "none",
    flowerSize: 0,
    widthMm: 18 * FT,
    depthMm: 18 * FT,
    heightMm: 22 * FT,
    native: true,
    description: "Copper peeling bark — tourist tree — open compound canopy",
  },
  {
    id: "sea_grape",
    name: "Sea grape",
    botanical: "Coccoloba uvifera",
    group: "trees",
    form: "sea_grape",
    foliage: rgb(40, 116, 48),
    foliageAlt: rgb(176, 72, 48),
    trunk: rgb(112, 104, 90),
    bloom: "none",
    flowerSize: 0,
    widthMm: 14 * FT,
    depthMm: 14 * FT,
    heightMm: 14 * FT,
    native: true,
    description: "Round leathery leaves, red veins — coastal windbreak",
  },
  {
    id: "frangipani",
    name: "Frangipani",
    botanical: "Plumeria rubra",
    group: "trees",
    form: "frangipani",
    foliage: rgb(42, 108, 52),
    trunk: rgb(210, 200, 172),
    flower: rgb(248, 118, 72),
    bloom: "star",
    flowerSize: 1.35,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 12 * FT,
    description: "Thick candelabra branches, sparse leaves, five-petal blooms",
  },
  {
    id: "bottlebrush",
    name: "Weeping bottlebrush",
    botanical: "Melaleuca viminalis",
    group: "trees",
    form: "bottlebrush",
    foliage: rgb(58, 108, 52),
    trunk: rgb(108, 88, 68),
    flower: rgb(196, 36, 42),
    bloom: "spike",
    flowerSize: 1.2,
    widthMm: 10 * FT,
    depthMm: 10 * FT,
    heightMm: 14 * FT,
    description: "Pendulous foliage with crimson bottlebrush spikes",
  },
  {
    id: "loquat",
    name: "Loquat",
    botanical: "Eriobotrya japonica",
    group: "trees",
    form: "broadleaf",
    foliage: rgb(62, 108, 48),
    trunk: rgb(96, 82, 64),
    flower: rgb(236, 214, 150),
    bloom: "cluster",
    flowerSize: 0.7,
    widthMm: 12 * FT,
    depthMm: 12 * FT,
    heightMm: 14 * FT,
    description: "Large corrugated leaves, fragrant winter panicles, yellow fruit",
  },
  {
    id: "red_maple",
    name: "Florida red maple",
    botanical: "Acer rubrum",
    group: "trees",
    form: "broadleaf",
    foliage: rgb(52, 118, 58),
    foliageAlt: rgb(176, 58, 48),
    trunk: rgb(86, 74, 62),
    bloom: "none",
    flowerSize: 0,
    widthMm: 16 * FT,
    depthMm: 16 * FT,
    heightMm: 22 * FT,
    native: true,
    description: "North / Central Florida — palmate leaves, red fall color",
  },
  {
    id: "mahogany",
    name: "West Indian mahogany",
    botanical: "Swietenia mahagoni",
    group: "trees",
    form: "broadleaf",
    foliage: rgb(42, 96, 48),
    trunk: rgb(78, 58, 44),
    bloom: "none",
    flowerSize: 0,
    widthMm: 20 * FT,
    depthMm: 20 * FT,
    heightMm: 24 * FT,
    native: true,
    description: "South Florida native — compound leaves, rounded crown",
  },

  // --- Shrubs ---
  {
    id: "hibiscus",
    name: "Tropical hibiscus",
    botanical: "Hibiscus rosa-sinensis",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(28, 96, 44),
    trunk: rgb(78, 64, 44),
    flower: rgb(214, 36, 58),
    bloom: "saucer",
    flowerSize: 1.45,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 6 * FT,
    description: "Large five-petal disks with a prominent column",
  },
  {
    id: "ixora",
    name: "Ixora",
    botanical: "Ixora coccinea",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(36, 92, 44),
    trunk: rgb(78, 64, 48),
    flower: rgb(214, 48, 42),
    bloom: "cluster",
    flowerSize: 0.85,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 4 * FT,
    description: "Dense glossy hedge with tight flower heads",
  },
  {
    id: "croton",
    name: "Croton",
    botanical: "Codiaeum variegatum",
    group: "shrubs",
    form: "variegated_shrub",
    foliage: rgb(48, 118, 42),
    foliageAlt: rgb(214, 72, 36),
    trunk: rgb(86, 70, 48),
    bloom: "none",
    flowerSize: 0,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 5 * FT,
    description: "Leathery leaves splashed yellow, orange, and red",
  },
  {
    id: "gardenia",
    name: "Gardenia",
    botanical: "Gardenia jasminoides",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(22, 76, 34),
    trunk: rgb(72, 60, 44),
    flower: rgb(250, 248, 238),
    bloom: "saucer",
    flowerSize: 1.1,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 4 * FT,
    description: "Dark glossy leaves, intensely fragrant white roses",
  },
  {
    id: "azalea",
    name: "Southern indica azalea",
    botanical: "Rhododendron indicum",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(48, 96, 48),
    trunk: rgb(82, 68, 52),
    flower: rgb(232, 96, 148),
    bloom: "saucer",
    flowerSize: 0.95,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 4 * FT,
    description: "North / Central Florida — spring flush of funnel blooms",
  },
  {
    id: "oleander",
    name: "Oleander",
    botanical: "Nerium oleander",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(62, 108, 58),
    trunk: rgb(96, 82, 64),
    flower: rgb(232, 128, 168),
    bloom: "cluster",
    flowerSize: 0.9,
    widthMm: 6 * FT,
    depthMm: 6 * FT,
    heightMm: 8 * FT,
    description: "Willow-like leaves, clustered flowers — all parts toxic",
  },
  {
    id: "firebush",
    name: "Firebush",
    botanical: "Hamelia patens",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(58, 108, 48),
    foliageAlt: rgb(176, 72, 42),
    trunk: rgb(92, 64, 48),
    flower: rgb(214, 72, 32),
    bloom: "trumpet",
    flowerSize: 0.75,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 6 * FT,
    native: true,
    description: "Native hummingbird shrub — orange-red tubular flowers",
  },
  {
    id: "plumbago",
    name: "Plumbago",
    botanical: "Plumbago auriculata",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(72, 128, 62),
    trunk: rgb(96, 86, 64),
    flower: rgb(98, 158, 214),
    bloom: "cluster",
    flowerSize: 0.8,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 4 * FT,
    description: "Sky-blue phlox-like clusters, soft mounding habit",
  },
  {
    id: "bougainvillea_shrub",
    name: "Bougainvillea (shrub)",
    botanical: "Bougainvillea glabra",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(48, 96, 50),
    trunk: rgb(92, 72, 52),
    flower: rgb(196, 28, 92),
    bloom: "bract",
    flowerSize: 1.2,
    widthMm: 6 * FT,
    depthMm: 6 * FT,
    heightMm: 7 * FT,
    description: "Paper magenta bracts on a woody mound — also on trellises",
  },
  {
    id: "podocarpus",
    name: "Podocarpus",
    botanical: "Podocarpus macrophyllus",
    group: "shrubs",
    form: "hedge",
    foliage: rgb(36, 82, 44),
    trunk: rgb(78, 68, 52),
    bloom: "none",
    flowerSize: 0,
    widthMm: 3 * FT,
    depthMm: 3 * FT,
    heightMm: 8 * FT,
    description: "Columnar yew-like hedge — the Florida privacy screen",
  },
  {
    id: "sweet_viburnum",
    name: "Sweet viburnum",
    botanical: "Viburnum odoratissimum",
    group: "shrubs",
    form: "hedge",
    foliage: rgb(48, 102, 52),
    trunk: rgb(82, 70, 54),
    bloom: "none",
    flowerSize: 0,
    widthMm: 6 * FT,
    depthMm: 5 * FT,
    heightMm: 8 * FT,
    description: "Large-leaf evergreen screen, fast and dense",
  },
  {
    id: "indian_hawthorn",
    name: "Indian hawthorn",
    botanical: "Rhaphiolepis indica",
    group: "shrubs",
    form: "round_shrub",
    foliage: rgb(52, 96, 52),
    trunk: rgb(86, 74, 58),
    flower: rgb(236, 196, 214),
    bloom: "cluster",
    flowerSize: 0.65,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 4 * FT,
    description: "Low mounding evergreen, pink-white spring clusters",
  },
  {
    id: "coontie",
    name: "Coontie",
    botanical: "Zamia integrifolia",
    group: "shrubs",
    form: "cycad",
    foliage: rgb(36, 86, 44),
    trunk: rgb(72, 62, 48),
    bloom: "none",
    flowerSize: 0,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 3 * FT,
    native: true,
    description: "Florida’s native cycad — stiff dark pinnate leaves from the crown",
  },
  {
    id: "agave",
    name: "Century plant / agave",
    botanical: "Agave americana",
    group: "shrubs",
    form: "rosette",
    foliage: rgb(148, 168, 142),
    foliageAlt: rgb(72, 78, 62),
    trunk: rgb(168, 166, 148),
    bloom: "none",
    flowerSize: 0,
    widthMm: 6 * FT,
    depthMm: 6 * FT,
    heightMm: 4 * FT,
    description: "Blue-gray swords with dark tips — architectural succulent",
  },
  {
    id: "pittosporum",
    name: "Pittosporum",
    botanical: "Pittosporum tobira",
    group: "shrubs",
    form: "round_shrub",
    foliage: rgb(58, 108, 62),
    trunk: rgb(88, 76, 58),
    flower: rgb(248, 246, 230),
    bloom: "cluster",
    flowerSize: 0.55,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 5 * FT,
    description: "Whorled glossy leaves, orange-blossom scented clusters",
  },
  {
    id: "duranta",
    name: "Golden dewdrop",
    botanical: "Duranta erecta",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(72, 138, 58),
    trunk: rgb(92, 78, 58),
    flower: rgb(118, 108, 214),
    bloom: "cluster",
    flowerSize: 0.7,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 6 * FT,
    description: "Sky-violet racemes, often gold-leaf cultivars",
  },
  {
    id: "thryallis",
    name: "Thryallis",
    botanical: "Galphimia glauca",
    group: "shrubs",
    form: "flowering_shrub",
    foliage: rgb(78, 128, 62),
    trunk: rgb(96, 82, 60),
    flower: rgb(232, 196, 48),
    bloom: "star",
    flowerSize: 0.65,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 5 * FT,
    description: "Fine yellow star flowers all warm season",
  },
  {
    id: "lantana",
    name: "Lantana",
    botanical: "Lantana camara",
    group: "shrubs",
    form: "round_shrub",
    foliage: rgb(62, 108, 48),
    trunk: rgb(92, 78, 56),
    flower: rgb(232, 148, 42),
    bloom: "cluster",
    flowerSize: 0.7,
    widthMm: 4 * FT,
    depthMm: 4 * FT,
    heightMm: 3 * FT,
    description: "Mounding clusters that shift yellow to orange to pink",
  },
  {
    id: "clusia",
    name: "Pitch apple / clusia",
    botanical: "Clusia rosea",
    group: "shrubs",
    form: "hedge",
    foliage: rgb(32, 86, 48),
    trunk: rgb(82, 70, 54),
    bloom: "none",
    flowerSize: 0,
    widthMm: 8 * FT,
    depthMm: 8 * FT,
    heightMm: 10 * FT,
    native: true,
    description: "Thick paddle leaves — South Florida hedge or small tree",
  },
  {
    id: "schefflera",
    name: "Dwarf schefflera",
    botanical: "Heptapleurum arboricola",
    group: "shrubs",
    form: "round_shrub",
    foliage: rgb(42, 102, 52),
    trunk: rgb(86, 72, 54),
    bloom: "none",
    flowerSize: 0,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 6 * FT,
    description: "Palmate umbrella leaflets — common foundation plant",
  },

  // --- Tropical accents ---
  {
    id: "bird_of_paradise",
    name: "Bird of paradise",
    botanical: "Strelitzia reginae",
    group: "tropical",
    form: "bird_of_paradise",
    foliage: rgb(42, 102, 52),
    trunk: rgb(196, 186, 92),
    flower: rgb(232, 118, 32),
    bloom: "bird",
    flowerSize: 1.5,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 5 * FT,
    description: "Clump of paddles with orange-and-blue crane flowers",
  },
  {
    id: "banana",
    name: "Banana",
    botanical: "Musa acuminata",
    group: "tropical",
    form: "banana",
    foliage: rgb(68, 148, 48),
    trunk: rgb(118, 138, 58),
    bloom: "none",
    flowerSize: 0,
    widthMm: 10 * FT,
    depthMm: 8 * FT,
    heightMm: 12 * FT,
    description: "Huge paddle leaves on a fleshy pseudostem, often tattered",
  },
  {
    id: "elephant_ear",
    name: "Elephant ear",
    botanical: "Alocasia macrorrhizos",
    group: "tropical",
    form: "elephant_ear",
    foliage: rgb(36, 96, 52),
    trunk: rgb(72, 96, 58),
    bloom: "none",
    flowerSize: 0,
    widthMm: 6 * FT,
    depthMm: 6 * FT,
    heightMm: 6 * FT,
    description: "Giant heart-shaped leaves on tall petioles",
  },
  {
    id: "philodendron",
    name: "Split-leaf philodendron",
    botanical: "Thaumatophyllum bipinnatifidum",
    group: "tropical",
    form: "philodendron",
    foliage: rgb(32, 92, 44),
    trunk: rgb(86, 96, 58),
    bloom: "none",
    flowerSize: 0,
    widthMm: 8 * FT,
    depthMm: 8 * FT,
    heightMm: 6 * FT,
    description: "Deeply lobed glossy leaves from a low woody stem",
  },
  {
    id: "bromeliad",
    name: "Bromeliad",
    botanical: "Aechmea fasciata",
    group: "tropical",
    form: "rosette",
    foliage: rgb(86, 138, 92),
    foliageAlt: rgb(196, 48, 78),
    trunk: rgb(168, 148, 92),
    flower: rgb(214, 64, 96),
    bloom: "spike",
    flowerSize: 1.1,
    widthMm: 2.5 * FT,
    depthMm: 2.5 * FT,
    heightMm: 2.5 * FT,
    description: "Banded urn rosette with a pink central inflorescence",
  },
  {
    id: "cordyline",
    name: "Ti plant",
    botanical: "Cordyline fruticosa",
    group: "tropical",
    form: "cordyline",
    foliage: rgb(148, 32, 58),
    foliageAlt: rgb(214, 72, 92),
    trunk: rgb(92, 62, 48),
    bloom: "none",
    flowerSize: 0,
    widthMm: 3 * FT,
    depthMm: 3 * FT,
    heightMm: 6 * FT,
    description: "Upright burgundy / pink swords on a cane stem",
  },
  {
    id: "macho_fern",
    name: "Macho fern",
    botanical: "Nephrolepis biserrata",
    group: "tropical",
    form: "fern",
    foliage: rgb(48, 122, 58),
    trunk: rgb(86, 78, 48),
    bloom: "none",
    flowerSize: 0,
    widthMm: 5 * FT,
    depthMm: 5 * FT,
    heightMm: 4 * FT,
    description: "Arching bipinnate fronds — the big Florida Boston-fern cousin",
  },
];

const BY_ID = new Map(FLORIDA_PLANTS.map((p) => [p.id, p]));

export function getFloridaPlant(
  id: string | undefined | null,
): FloridaPlant | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

export function isFloridaPlantId(id: string | undefined | null): boolean {
  return !!id && BY_ID.has(id);
}

export function isYardLandscapeStructureId(
  id: string | undefined | null,
): boolean {
  return (
    id === "planter" || id === "trellis" || id === "trellis_arbor"
  );
}

export function isLandscapingCatalogId(id: string | undefined | null): boolean {
  return isFloridaPlantId(id) || isYardLandscapeStructureId(id);
}

export function plantsInGroup(group: PlantGroup): FloridaPlant[] {
  return FLORIDA_PLANTS.filter((p) => p.group === group);
}

export function plantCssColor(c: PlantColor): string {
  return `rgb(${c.r}, ${c.g}, ${c.b})`;
}

export function plantDisplayName(plant: FloridaPlant): string {
  return plant.native ? `${plant.name} · native` : plant.name;
}

export function plantDescription(plant: FloridaPlant): string {
  const bits = [plant.botanical];
  if (plant.native) bits.push("Florida native");
  if (plant.description) bits.push(plant.description);
  return bits.join(" — ");
}
